name: Centos-7 test

on:
  workflow_dispatch:
  
jobs:
  install:
    runs-on: macos-latest
#     strategy:
#       fail-fast: false
#       matrix:
#         rspm: [true, false]
    steps:
      - uses: assignUser/actions/setup-r@pin-mac-4.2.0
        with:
          r-version: 4.2
