name: Centos-7 test

on:
  workflow_dispatch:
  
jobs:
  install:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - run: which ccache
      - run: echo $PATH
      - uses: r-lib/actions/setup-r@v2
      - run: which ccache
      - run: echo $PATH
