name: Centos-7 test

on:
  workflow_dispatch:
  
jobs:
  install:
    runs-on: windows-latest
#     strategy:
#       fail-fast: false
#       matrix:
#         rspm: [true, false]
    steps:
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 3.6
          use-public-rspm: true
      - uses: actions/checkout@v3
        with:
          repository: apache/arrow
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: 'r'

  install-devel:
    runs-on: windows-latest
    steps:
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'devel'
      - uses: actions/checkout@v3
        with:
          repository: apache/arrow
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: 'r'
