name: Centos-7 test

on:
  workflow_dispatch:
  
jobs:
  install:
    runs-on: windows-latest
    steps:
      - uses: r-lib/actions/setup-r@v2
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
