name: Centos-7 test

on:
  workflow_dispatch:
  
jobs:
  install:
    runs-on: windows-latest
#     strategy:
#       fail-fast: false
#       matrix:
#         rspm: [true, false]
    steps:
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.2
