name: Centos-7 test

on:
  workflow_dispatch:
  
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - run: |
          source agent-start "$GITHUB_ACTION"
          set -eu
          mkdir a
          mkdir b
          touch a/test.txt
          cp a/* b/
        
