name: Centos-7 test

on:
  workflow_dispatch:
  
jobs:
  install:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        rspm: [true, false]
    steps:
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: ${{ matrix.rspm }}
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: 'NA'
          packages: any::tidyverse
