name: Centos-7 test

on:
  workflow_dispatch:
  
jobs:
  install:
    runs-on: ubuntu-latest
    container: "rstudio/r-base:4.1-centos7"
    strategy:
      fail-fast: false
      matrix:
        not-cran: ["TRUE", "FALSE"]
    steps:
      - name: Install system requirements
        shell: bash
        run: |
          if [ "`which dnf`" ]; then
            dnf install -y libcurl-devel openssl-devel
          elif [ "`which yum`" ]; then
            yum install -y libcurl-devel openssl-devel
          elif [ "`which zypper`" ]; then
            zypper install -y libcurl-devel libopenssl-devel
          else
            apt-get update
            apt-get install -y libcurl4-openssl-dev libssl-dev
          fi
      - uses: r-lib/actions/setup-r@v2
        with:
          install-r: false
      - name: Test linux binary
        env:
          NOT_CRAN: ${{ matrix.not-cran }}
        shell: Rscript {0}
        run: |        
          install.packages(
            "arrow",
            verbose = TRUE
          )

          library(arrow)
          read_parquet(system.file("v0.7.1.parquet", package = "arrow"))
