name: Centos-7 test

on:
  workflow_dispatch:
  
jobs:
  install:
    runs-on: macos-11
    defaults:
      run:
        shell: bash
    steps:
      - uses: r-lib/actions/setup-r@v2
      - shell: Rscript {0}
        env: 
          ARROW_R_DEV: TRUE
        run: |
          install.packages("arrow")
          install.packages(c("arrow","cpp11"),
            type = "binary",
            repos = c("https://nightlies.apache.org/arrow/r", "https://cloud.r-project.org")
          )

          cat("Remove old arrow version.\n")
          remove.packages("arrow")
          install.packages("arrow", type = "source", repos = "https://nightlies.apache.org/arrow/r")
          
          print(packageVersion("arrow"))
