name: test

on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: test
        run: |
          touch test.txt
          echo "::set-output path=__some__thing"
      - uses: actions/upload-artifact@v3
        with:
          name: r-pkg${{ steps.test.outputs.path }}
          path: test.txt
