name: Velox Wheel
on:
  push:
  
jobs:
  test_wheels:
    name: Test wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-11, macos-12]
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - run: |
          python -m pip install --upgrade pip
          python -m pip install packaging
      - shell: python {0}
        run: |
          from packaging.tags import sys_tags
          tags = sys_tags()
          from distutils import util
          print(util.get_platform())
          for tag in list(tags)[:3]:
            print(tag.interpreter, tag.abi, tag.platform)


      - run: |
          gh run -R facebookincubator/velox download 4115657665
          cd wheels
          mv pyvelox-0.0.1a0+bba0a2e-cp37-cp37m-macosx_11_0_x86_64.whl pyvelox-0.0.1a0+bba0a2e-cp37-cp37m-macosx_10_15_x86_64.whl 
          python3.7 -m pip install  pyvelox-0.0.1a0+bba0a2e-cp37-cp37m-ma${{ startsWith(matrix.os, 'ubuntu') && 'ny*' || 'cos*' }}
      - name: Test Wheels
        shell: python {0}
        run: |
          import pyvelox.version as pvv
          import pyvelox.pyvelox as pv
          print(pvv.git_version)
          pv.Expression.from_string("a + b")
