name: dispatch-test

on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - run: sudo apt install libcurl4-openssl-dev
      - uses: r-lib/actions/setup-r@v2
      - uses: actions/checkout@v3
        with:
          repository: apache/arrow
          path: arrow
      - run: |
          cd arrow/r
          sed -i.bak -E -e \
            's/(^Version: )([0-9]+\.[0-9]+\.[0-9]+).*$/\18.0.0/' \
            DESCRIPTION
          head DESCRIPTION
          
          sed -i.bak -E -e 's/os <- find_available_binary\(os\)$/os <- "ubuntu-22.04"/' tools/nixlibs.R
          rm -f tools/nixlibs.R.bak
          rm -f DESCRIPTION.bak
          make sync-cpp
          R CMD build --no-build-vignettes .
          Rscript -e "install.packages('arrow')"
      - name: Set dev repo
        shell: bash
        run: |
          # It is important to use pwd here as this happens inside a container so the 
          # normal github.workspace path is wrong.
          echo "options(arrow.dev_repo ='https://nightly.wujciak.de/r')" >> ~/.Rprofile
      - shell: Rscript {0}
        if: true
        env:
          NOT_CRAN: "TRUE"
          ARROW_R_DEV: "TRUE"
        run: |
          install.packages("arrow/r/arrow_8.0.0.tar.gz")
          library(arrow)
          read_parquet(system.file("v0.7.1.parquet", package = "arrow"))
