name: Velox Wheel
on:
  push:
  
jobs:
  test_wheels:
    name: Test wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-11, macos-12]
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - run: python -m pip install packaging
      - shell: python {0}
        run: |
          import packaging
          tags = sys_tags()
          for tag in list(tags)[:3]:
            print(tag.interpreter, tag.abi, tag.platform)


      - run: |
          gh run -R facebookincubator/velox download 4115657665
          cd wheels
          python3.7 -m pip install  pyvelox-0.0.1a0+bba0a2e-cp37-cp37m-ma${{ startsWith(matrix.os, 'ubuntu') && 'ny*' || 'cos*' }}
      - name: Test Wheels
        shell: python {0}
        run: |
          import pyvelox.version as pvv
          import pyvelox.pyvelox as pv
          print(pvv.git_version)
          a = pv.from_list([1, 2, 3, None])
          b = pv.from_list([4, 5, None, 6])
          c = expr.evaluate(["a", "b"], [a, b])
      
