name: dispatch-test

on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: r-lib/actions/setup-r@v2
      - shell: Rscript {0}
        run: |
          Sys.setenv("NOT_CRAN" = TRUE) 
          install.packages("arrow")
          library(arrow)
          read_parquet(system.file("v0.7.1.parquet", package = "arrow"))
