name: dispatch-test

on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - run: sudo apt install libcurl4-openssl-dev
      - uses: r-lib/actions/setup-r@v2
      - shell: Rscript {0}
        env:
          NOT_CRAN: "TRUE"
          ARROW_R_DEV: "TRUE"
          LIBARROW_BINARY: "FALSE"
        run: |
          install.packages("arrow")
          library(arrow)
          read_parquet(system.file("v0.7.1.parquet", package = "arrow"))
