name: deps-test

on:
  push:
  workflow_dispatch:
  
jobs:
  ubuntu:
    name: AMD64 Ubuntu ${{ matrix.ubuntu }} R ${{ matrix.r }} Force-Tests ${{ matrix.force-tests }}
    runs-on: ubuntu-latest
    steps:
      - uses: r-lib/actions/setup-r@v2

