name: dispatch-test

on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            let res = await github.rest.issues.get({
            owner: context.repo.owner,
            repo: context.repo.repo})
            console.log(res)
