name: Unlisted Test


on:
  workflow_run:
    workflows: ["fails", "succeeds"]
    types:
      - completed

jobs:
  on-success:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request'}} 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            const [owner, repo] = '${{ github.repository }}'.split("/")
            github.rest.repos.createCommitStatus({
              owner: owner,
              repo: repo,
              sha: '${{ github.event.workflow_run.head_sha}}',
              state: 'success',
              target_url: '${{ github.event.workflow_run.html_url }}',
              description: 'Results commented!'
            })
  on-failure:
    needs: on-success
    if: ${{ (github.event.workflow_run.conclusion == 'failure' || failure()) && github.event.workflow_run.event == 'pull_request'}} 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            const [owner, repo] = '${{ github.repository }}'.split("/")
            github.rest.repos.createCommitStatus({
              owner: owner,
              repo: repo,
              sha: '${{ github.event.workflow_run.head_sha}}',
              state: 'failure',
              target_url: '${{ github.event.workflow_run.html_url }}',
              description: 'Workflow failed!'
            })
